apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: containerize-app-mysql-servic-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
