---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-service-secret
stringData:
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "database"
  POSTGRES_PORT: "5432"
  POSTGRES_ROOT_HOST: "localhost"
