---
apiVersion: v1
kind: Service
metadata:
  name: containerize-app-redis-service
spec:
  selector:
    app: containerize-app-redis-service
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
