---
apiVersion: v1
kind: Service
metadata:
  name: containerize-app-php-service
spec:
  selector:
    app: containerize-app-php-service
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
