---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-php
  labels:
    app: app-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-php
  template:
    metadata:
      labels:
        app: app-php
    spec:
      containers:
        - name: app-php
          image: marouanetesting/php:v1.1
          ports:
            - containerPort: 9000
