---
apiVersion: v1
kind: Service
metadata:
  name: containerize-app-mysql-service
spec:
  selector:
    app: containerize-app-mysql-service
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
