name: CI-CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Install dependencies
        run: |
          cd app-php
          composer install --prefer-dist --no-interaction --no-progress

  cd:
    runs-on: ubuntu-latest
    needs: ci
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push PHP image
        run: |
          docker build -t marouanetesting/php:v1.1 ./app-php
          docker push marouanetesting/php:v1.1

      - name: Build & Push NGINX image
        run: |
          docker build -t marouanetesting/nginx:v1.1 ./nginx
          docker push marouanetesting/nginx:v1.1

      - name: Build & Push PostgreSQL image
        run: |
          docker build -t marouanetesting/postgres:v1.1 ./database/postgres
          docker push marouanetesting/postgres:v1.1

      - name: Build & Push Redis image
        run: |
          docker build -t marouanetesting/redis:v1.1 ./redis
          docker push marouanetesting/redis:v1.1